stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  script:
    - echo Building project 
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    #- docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker build -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHORT_SHA"
  tags:
    - docker2  

deploy:
  stage: deploy
  image: jonaskello/docker-and-compose
  script:
    - echo Deploy project
    - docker login -u "$CI_REGISTRY_USER" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose down
    - docker-compose up -d --build
  tags:
    - docker2